language: python
matrix:
    include:
        - python: 3.6
          env: TOXENV=py36-django31
        - python: 3.6
          env: TOXENV=py36-django32
        - python: 3.7
          env: TOXENV=py37-django31
        - python: 3.7
          env: TOXENV=py37-django32
        - python: 3.8
          env: TOXENV=py38-django31
        - python: 3.8
          env: TOXENV=py38-django32
        - python: 3.9
          env: TOXENV=py39-django31
        - python: 3.9
          env: TOXENV=py39-django32
install:
    - pip install Django>=3.1
    - pip install coveralls==1.3.0
    - pip install coverage==4.5.1
    - pip install tox-travis==0.10
before_script:
    - coverage erase
script:
    - coverage run --source=eav runtests; tox
after_success:
    - COVERALLS_REPO_TOKEN=71NkMDQFpFKB9QYXoK12LYuWUEmQ2wD6V coveralls
